# Generated by Django 3.2.9 on 2021-12-27 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='省份')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='城市')),
                ('summary', models.TextField(max_length=1000, verbose_name='概览')),
                ('policy', models.TextField(max_length=10000, verbose_name='详细政策')),
                ('image', models.ImageField(blank=True, upload_to='quickcheck', verbose_name='图片')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='最新更新时间')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_province', to='quickcheck.province', verbose_name='省份')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
    ]
