# Generated by Django 3.2.9 on 2021-12-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickcheck', '0002_city_update_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='policy_enc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='summary_enc',
            field=models.BooleanField(default=False),
        ),
    ]
