# Generated by Django 3.2.9 on 2021-12-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickcheck', '0003_auto_20211227_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='policy_enc',
        ),
        migrations.RemoveField(
            model_name='city',
            name='summary_enc',
        ),
    ]
