# Generated by Django 3.2.9 on 2021-12-27 17:09

from django.db import migrations
import quickcheck.models


class Migration(migrations.Migration):

    dependencies = [
        ('quickcheck', '0004_auto_20211227_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='policy',
            field=quickcheck.models.CustomEncryptField(max_length=10000, verbose_name='详细政策'),
        ),
        migrations.AlterField(
            model_name='city',
            name='summary',
            field=quickcheck.models.CustomEncryptField(max_length=1000, verbose_name='概览'),
        ),
    ]
