# Generated by Django 3.2.9 on 2021-12-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.verifier', verbose_name='验证'),
        ),
    ]
